#\u8CC7\u6599\u5EAB\u8207JPA\u8A2D\u5B9A
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/webredgood?options=-c%20timezone=Asia/Taipei
spring.datasource.username=postgres
spring.datasource.password=1111

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# \u8A2D\u5B9A\u4E0D\u540C\u5957\u4EF6\u7684 Log \u7B49\u7D1A
logging.level.root=INFO
logging.level.com.aiinpocket.webredgood=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# \u8F38\u51FA\u5230\u6A94\u6848
logging.file.name=logs/webredgood.log
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# 錯誤處理設定（生產環境請設為 false）
app.error.expose-detail=true
